### PR TITLE
Fix header warning with Qt 5.6.0.

### PR DESCRIPTION
**Pull request by koppi**
Fixed a warning with Qt 5.6.1:
```
Header <QtDesigner/QDesignerCustomWidgetInterface> is deprecated.
Please include <QtUiPlugin/QDesignerCustomWidgetInterface> instead.
```
Tested to work with Qt 5.5.1 and Qt 5.6.0.

### CODE REVIEW

**Comment by ArcEye** [comment]
Thanks

I am still using Qt 5.4, because 5.5 was broken

I will leave the PR here for now until I update and test that 5.6 works with all my other stuff

**Comment by koppi** [comment]
Does this change work with Qt 5.4? We should add #ifdefs in this case.

**Comment by ArcEye** [comment]
No, the header locations are different, so there will have to be a test for Qt version.

Why can't they leave things alone!

**Comment by ArcEye** [comment]
Fixed with https://github.com/ArcEye/QGCodeEditor/commit/9205ab1e9974ca99bed934edb7e14ac643e6e08a
Needed test of version, seems to work OK with 5.6 and 5.4 now

**Comment by koppi** [comment]
Thank's a lot!

**Pull request closed without merging**
